### ISSUE TITLE
9.2장 5번째 줄 리다이렉트 문제

### ISSUE THREAD

**Issue by Oslint** [rinthel/rust-lang-book-ko#102]
![image](https://user-images.githubusercontent.com/37634063/40585480-59dc6bce-61ee-11e8-9b80-c3c4b3e476bb.png)

위 사진의 Result 타입으로 잠대된 실패 다루기 부분을 클릭하면 2장으로는 넘어가지는데 Result 타입으로 잠대된 실패 다루기절로는 넘어가지 않습니다.

**Comment by rinthel** [comment]
수정했습니다 오류 레포팅 감사합니다!
