### ISSUE TITLE
10.2의 트레잇 바운드절 오타

### ISSUE THREAD

**Issue by Oslint** [rinthel/rust-lang-book-ko#105]
+를 이용하면 하나의 제네릭 타입에 대해 여러 개의 트레잇 바운드를 특정할 수 있습니다. 만일 함수 내에서 타입 T에 대해 summary 메소드 뿐만 아니라 형식화된 출력을 사용하길 원한다면, 트레잇 바운드 T: Summarizable + Display₩를 이용할 수 있습니다. 이는T가Summariable과Display` 둘다 구현한 어떤 타입이어야 함을 의미합니다.
이 부분에서 Summarizable + Display₩의 ₩를 없애야 할 것 같습니다.

**Comment by rinthel** [comment]
감사합니다!
