### ISSUE TITLE
10.2의 트레잇 바운드를 사용하여 largest 함수 고치기절의 오타들

### ISSUE THREAD

**Issue by Oslint** [rinthel/rust-lang-book-ko#106]
![image](https://user-images.githubusercontent.com/37634063/40644418-278d4b36-635e-11e8-9039-10bc0cda9bb6.png)
이 부분 1번재 주르이 제한하길 원지 -> 치로 고쳐야 되고
4번째 줄의 힙 할당은 많은 양으 -> 의로 고쳐야 될 것 같고

![image](https://user-images.githubusercontent.com/37634063/40644449-3ccd7700-635e-11e8-9f63-ec5bee2f1e36.png)
이 부분 5번째 줄의 메소드를 호ㅜㄹ -> 출로 고쳐야 될 것 같습니다.

**Comment by rinthel** [comment]
감사합니다!
