### ISSUE TITLE
10.3의 오타들

### ISSUE THREAD

**Issue by Oslint** [rinthel/rust-lang-book-ko#108]
![image](https://user-images.githubusercontent.com/37634063/40657462-ecbfa1a0-6382-11e8-8d38-78ed19849e34.png)
첫번째 문단의 밑줄친 부분의 라이브를 라이프로 변경해야 할 것 같습니다.

![image](https://user-images.githubusercontent.com/37634063/40815459-9af439a2-6581-11e8-972b-f24036ddada1.png)
라이프타임 부분쪽에 있습니다. 밑줄친 부분의 이라ㅗ를 이라고로 변경해야 할 것 같습니다.

**Comment by rinthel** [comment]
감사합니다!
