### ISSUE TITLE
번역문의 링크

### ISSUE THREAD

**Issue by djKooks** [rinthel/rust-lang-book-ko#114]
안녕하세요, 공부중에 잘 참고하고 있습니다!

한글 문서를 찾던 와중에, 아래와 같은 페이지가 있는데, 지금 번역중이신 자료의 링크를 여기 올려도 괜찮을까요?
https://github.com/ctjhoa/rust-learning/blob/master/ko_KR.md

여기에 링크된 공식문서 번역자료는 번역이 중단된 지 2년이 넘은 것 같네요;;;

**Comment by rinthel** [comment]
안녕하세요! 요즘 너무 정신없이 바빠서 이제사 봅니다;
물론 올리셔도 괜찮습니다~ 많은 자료가 모여서 좋은 참고 페이지가 되면 좋겠네요!

**Comment by djKooks** [comment]
감사합니다! 참고해주세요~
https://github.com/ctjhoa/rust-learning/pull/138
