### ISSUE TITLE
안녕하세요, 번역 참여하고 싶습니다. ^^

### ISSUE THREAD

**Issue by jenix21** [rinthel/rust-lang-book-ko#13]
1번째 버전 번역에도 참여했었는데요, 2번째 버전도 참여해 보고 싶습니다.

https://www.penflip.com/jenix21

**Comment by rinthel** [comment]
환영합니다 @jenix21 님 :)
collaborator 초청 드렸으니 확인하시구요,
아래 제가 달아논 이슈들 중에 맘에 드시는거 할당 하시고 브랜치 생성해서 진행하시면 될거 같습니다!
의논하실거나 궁금한 사항 있으시면 말씀 주세요-

**Comment by ParkHanbum** [comment]
@rinthel  
페북보고 왔습니다. 참여 신청 합니다~

이전 참여 내역.
https://www.penflip.com/hanbum
https://hanbum.gitbooks.io/rustbyexample/content/

**Comment by rinthel** [comment]
@ParkHanbum 님 환영합니다!
collaborator 초청 드렸습니다. 이슈로 달아놓은 장 중에 원하시는 거에 assign하시고 진행해주심 감사하겠습니다!

**Comment by tolskais** [comment]
@rinthel 
rust에 관심이 많은 와중에 본 프로젝트를 발견했습니다. rust에 친숙하지 않아도 서문이나 2장 부분은 참여할 수 있을 것 같은데 가능할까요?

**Comment by rinthel** [comment]
@tolskais 님 환영합니다 :)
저도 막상 포크했지만 번역은 초보입니다.
2장부텀 진행하시면 괜찮을듯 합니다! 1장은 앞으로도 수정될 상황을듯 싶어서요.
collaborator로 등록해두겠습니다-

**Comment by superjiy** [comment]
@rinthel 
번역 작업 참여하고 싶습니다.

**Comment by rinthel** [comment]
@superjiy 안녕하세요~ 환영합니다! collaborator로 등록해두었습니다~
