### ISSUE TITLE
안녕하세요

### ISSUE THREAD

**Issue by baguniz** [rinthel/rust-lang-book-ko#134]
안녕하세요. 러스트를 처음부터 배우고 있는 baguniz라고 합니다. 먼저 귀중한 시간을 내 주셔서 러스트 북을 한글로 번역해주셔서 감사합니다. 덕분에 언어장벽 없이 러스트를 접할 수 있게 되었습니다.

이번에 러스트 한글 번역 리포지토리에 이슈를 남기게 된 것은 몇가지 오탈자와 함께 번역 관련해서 궁금한 점이 있기 때문입니다. 바쁘시더라도 한번 확인해주시면 감사하겠습니다.

### 번역 용어 인덱스의 필요성
러스트 한글판은 용어들을 모두 한글화했는데 프로그래밍을 하다보면 원어의 용어가 필요할 때가 있습니다. rust-lang-book을 퍼블리싱된 페이지로 접하는 경우 별도로 번역 용어가 정리된 곳이 없는게 조금 불편했습니다. README.md분만 아니라 퍼블리싱 페이지에 번역 용어들이 정리된 페이지가 있었으면 좋겠습니다.

### 설치하기 섹션
설치하기 섹션에서 윈도우 환경의 경우에는 다음과 같이 입력하라고 나와있습니다:
```bash
> dir /B %= the /B option says to only show the file names =%
main.exe
main.pdb
main.rs
```
하지만 실제로는 %= ~ =% 란을 제외해야 정상적으로 출력이 됩니다.

그리고 바로 아래 `$ ./main # or .\main.exe on Windows` 라고 코드 블록이 만들어져 있는 부분은 다음과 같이 수정되면 더 깔끔하지 않을까 생각이 드네요.
`$ ./main` (윈도우는 `>.\main`)

위 섹션 이슈는 rust-lang-book 원판에도 그대로 나와있는 문제라 따로 수정을 가하지는 않으신 것 같습니다.

읽어주셔서 감사합니다.

**Comment by rinthel** [comment]
좋은 의견 감사드립니다 :)

번역 용어의 경우, 원문을 검색해도 그대로 나올수 있도록 하기 위해서 용어가 첫번째로 사용된 곳에는 원문을 괄호 안에 넣어 병기하도록 했습니다만, 역시 이것만으로는 좀 부족하나 싶기도 했지요.

원문에는 없지만, Glossary라는 페이지를 하나 만들어다가 여기에 (한글: 영어) 혹은 (영어: 한글) 형태로 번역 용어를 정리하면 어떨까 합니다.

설치하기 섹션의 `%= ~ =%` 부분은 아마도 추측컨데 주석을 표현하고 싶어하지 않았나 싶습니다 ㅎㅎ;
원문에서 일부러 두고 있는듯 하니 일단은 그냥 두겠습니다.

그리고 아래의 main.exe 등은 `dir`을 실행했을때 나타나는 파일 목록을 나타낸 것으로 보입니다.

Glossary와 관련된 작업은 따로 이슈를 만들어두겠습니다!

**Comment by baguniz** [comment]
앗 빠른 피드백과 리뷰 감사합니다! 즐거운 러스트코딩 되세요.
