### ISSUE TITLE
안녕하세요, 번역 작업에 참가하고 싶습니다.

### ISSUE THREAD

**Issue by han-minhee** [rinthel/rust-lang-book-ko#153]
Rust를 공부하던 중 혹시 번역이 있으면 기여하려는 생각이 들어 
프로젝트를 찾아보니 꽤나 진전이 되었네요 ^^
얼마나 기여할 수 있을지 모르겠지만, 조금씩이라도 기여해보고 싶습니다.
Collaborator로 초대해주시면 감사하겠습니다.

**Comment by okms00909** [comment]
멋지시네요!

다만, 부록 부분을 번역하실 예정이시라면 중복 작업 방지를 위해 #154 이슈를 참고해주시고, 맡으실 부분을 정하시고 나면 정한 부분을 이슈로 등록해주시면 감사하겠습니다!
