### ISSUE TITLE
mdbook - travis ci ~ gh-pages 연동

### ISSUE THREAD

**Issue by sshplendid** [rinthel/rust-lang-book-ko#155]
[mdbook userguide - Continuos Integration](https://rust-lang-nursery.github.io/mdBook/continuous-integration.html#deploying-your-book-to-github-pages) 부분을 보면 Travis CI와 연동해서 자동으로 푸시할 수 있게 되어 있는데요. #3 이슈를 보면 rinthel 님께서도 이전에 작업하셨던 것으로 보입니다.

travis 연동에 대해 어떻게 생각하시는지 의견 여쭙습니다.

**Comment by rinthel** [comment]
좋다고 생각합니다 :)
여태까지는 제가 수동으로 build를 위한 브랜치를 따로 만들고 master에 쌓인 그간의 변경 내역을 머지시킨뒤 수동으로 빌드를 하고 있었습니다. 일종의 release 브랜치를 만든 셈이지요.
이제는 번역이 거의 대부분 되어있고, hotfix 개념으로 바로 빌드되어 퍼플리싱 되는 편이 좋을거라는 생각이 드는군요.
제가 한번 Travis쪽을 공부해보고 시도해보겠습니다 ㅎㅎ

**Comment by rinthel** [comment]
e7046564542fe44e33d48fd378836cd395624eaa 4c2c61360393daebf33822cdc94e796b4ac423b6 b03b61e30607665aa6ac83392a663556c3ed8952 433f6ff7fdb0aa7eb05dbcf7a9af51663525128d
요렇게 해서 작업이 완료되었습니다 :D 이제 master에 merge가 되면 자동으로 5분내에 deploy 될겁니다!
