### ISSUE TITLE
번역 작업에 참여하고 싶습니다.

### ISSUE THREAD

**Issue by So-chiru** [rinthel/rust-lang-book-ko#161]
최근 Rust에 관심을 가지게 되었는데, 한국어 번역에 기여하면서 배워가는 것이 좋을 것 같아 번역에 참여 신청해 봅니다. ^^

**Comment by rinthel** [comment]
제가 이걸 이제사 봤네요; 바로 colleague로 등록해두겠습니다!

**Comment by So-chiru** [comment]
감사합니다! 오탈자같은 것들 열심히 보겠습니다! :)
