### ISSUE TITLE
4-1장 소유권 규칙 부분에 대한 번역 개선

### ISSUE THREAD

**Issue by skicombinator** [rinthel/rust-lang-book-ko#164]
안녕하세요.
우선 문서 번역해주셔서 감사합니다. 잘 읽고 있습니다.

4-1장 소유권 규칙에서:
>  1. 러스트의 각각의 값은 해당값의 오너(owner)라고 불리우는 변수를 갖고 있다.
>  2. 한번에 딱 하나의 오너만 존재할 수 있다.
>  3. 오너가 스코프 밖으로 벗어나는 때, 값은 내려간다(dropped).

이라고 번역이 되어 있는데, 마지막 3번 부분에서 `값은 내려간다` 부분이 조금 어색한 것 같습니다.
원문이 `When the owner goes out of scope, the value will be dropped.` 인걸로 보아, 값이 `내려간다`기 보다는 `버려진다`는 의미에 더 가깝다고 봅니다.

감사합니다.

**Comment by rinthel** [comment]
이걸 이제사 처리하게됐네요 죄송합니다; #16328ad 에서 반영되었습니다!

**Comment by skicombinator** [comment]
감사합니다. 번역해주신 것 잘 보고있습니다!
