### ISSUE TITLE
해석 토의 `bound`

### ISSUE THREAD

**Issue by ParkHanbum** [rinthel/rust-lang-book-ko#18]
bound에 대한 해석에 대한 토의

경우1) 
Like immutable variables, constants are also values that are bound to a name and are not allowed to change,

경우2)
When a variable is immutable, that means once a value is bound to a name, you can’t change that value. 

binding 혹은 bind는 추상적인 표현이고 아직 제대로 번역된 경우를 보지 못했습니다. 
이런 단어가 어떨 때 사용되는지 경우를 모아놓으면 좋은 아이디어가 나올 수 있을 것 같습니다. 

제 생각에는 어떤 expression이나 value가 프로그램 안에서 다뤄지기 위해 variables 혹은 constants에 ('묶이는', '할당되는', '적용되는', 대입되는', '대표되는', '선언되는','명명되는') 시에 binding 혹은 bind된다고 사용되는 것 같습니다.

**Comment by rinthel** [comment]
넵 저도 4장 진행중에 비슷한 부분을 만났었는데, 일단은 '묶이다'로 선택하여 진행했었습니다.

제 생각에도 이 bind / bound라는 말이 많이 추상화된 형태로 들립니다. 다만 할당이나 혹은 대입과 같은 용어의 경우 실제로 CPU와 메모리에서 어떤 동작을 수행하는 뜻으로 읽힐 가능성이 큰 데에 비해, 저는 bind / bound라는 말은 그런 동작 없이 그냥 logical하게 '묶음짓는다'는 뜻으로 읽었습니다.

**Comment by rinthel** [comment]
4장 1절에 나온 bind / bound의 경우를 모아보면 이렇습니다.

> “Bind the value `5` to `x`; then make a copy of the value in `x` and bind it to `y`.”

> the second line would make a copy of the value in `s1` and bind it to `s2`.

4장 1절에는 이러한 상황을 그림으로도 그려놨는데, 변수의 이름이 `s1`인 `String`은 실제 `String`을 위한 메모리 공간이 할당되고, 거기에 `s1`이라는 네임태그를 달아놓은 식으로 표현했습니다.

**Comment by jenix21** [comment]
이름과 값이 연결 되어 있다는 표현으로 bind/bound 가 쓰인 것으로 보고,
단어 그대로의 뜻으로 '묶다/묶이다'로 쓰는것이 괜찮을 것 같습니다.

**Comment by tolskais** [comment]
2장에서도 비슷한 쓰임새가 나옵니다.

> We bind `guess` to the expression `guess.trim().parse()`

> This line will create a new variable named `foo` and bind it to the value `bar`.

특정 객체나 값을 변수에 이름을 붙인다라는 느낌으로 썼다는 생각이 들어 "묶이다" 라고 해석하고 있었습니다. 다만 다른 언어에 익숙한 분들이 보기에는 좀 어색한 표현이 아닐까 싶기도 해서 고민 중이었네요.

**Comment by ParkHanbum** [comment]
저도 '묶인다'는 표현이 생각보다 매끄럽지 않게 다가와서 고민 중입니다. 
예를 들어, let x = 5 의 구문이 x와 5가 묶인다 라고 하면, let y = 5 의 구문도 y와 5가 묶인다가 되는데
그럼 여기서 5는 x와 y의 공통분모냐...? 하면 아니죠. 두 변수는 각기 다른 메모리 주소에 5를 갖습니다.
(일반적으로? 보통은?)

let x; 와 같은 구문은 declare variable이라고 표현합니다.
let x = 5; 와 같이 변수에 값이 대입되는 경우에만 bind라는 표현이 사용됩니다. 
하지만 또 대입이라고 표현하면 이것도 애매합니다.
