### ISSUE TITLE
4-3장의 코드에 누락된 부분이 있습니다.

### ISSUE THREAD

**Issue by denebu** [rinthel/rust-lang-book-ko#191]
안녕하세요. 우선 훌륭한 번역 문서를 만들어주셔서 감사합니다.
바로 본론부터 얘기하자면, [ch04-03-slices.md](https://github.com/rinthel/rust-lang-book-ko/blob/master/second-edition/src/ch04-03-slices.md) 의 `스트링 리터럴은 슬라이스입니다` 섹션 바로 윗 문단에 등장하는 코드에 누락된 부분이 있습니다.

```rust
fn main() {
    let mut s = String::from("hello world");

    let word = first_word(&s);

    s.clear(); // Error!
}
```

이 코드를 본문에 앞서 서술한 `first_word` 함수를 구현한 채 그대로 실행시키면, 본문에 서술되어 있는 컴파일 오류가 뜨는 게 아니라, 다음과 같이 경고가 뜹니다.

```
warning: unused variable: `word`
 --> src/main.rs:4:9
  |
4 |     let word = first_word(&s);
  |         ^^^^ help: consider prefixing with an underscore: `_word`
  |
  = note: `#[warn(unused_variables)]` on by default
```

해당 코드는 "the book" 원문에는 다음과 같이 나와있고, 이렇게 작성하면 원하는 결과 (컴파일 오류) 가 나옵니다.

```rust
fn main() {
    let mut s = String::from("hello world");

    let word = first_word(&s);

    s.clear(); // error!

    println!("the first word is: {}", word);
}
```

보시다시피, 마지막 줄이 추가되어 있습니다.

이 부분을 고치고 싶은데, 혹시 제가 PR을 넣으면 될까요? 괜찮으시다면, 다른 분이 넣어주셔도 될 것 같습니다.

**Comment by rinthel** [comment]
감사합니다! 한줄 추가하는 간단한 수정이라 제가 바로 고쳐서 푸시했습니다 😃
