### ISSUE TITLE
안녕하세요, 한국어 번역 참여하고싶습니다.

### ISSUE THREAD

**Issue by YOUNGZOO** [rinthel/rust-lang-book-ko#20]
열심히 해보고 싶습니다!

**Comment by rinthel** [comment]
환영합니다!
collaborator 초대 보냈으니 확인하시구요 :)
음 현재 frozen column에 있는 모든 이슈는 다른 분들이 가져가셨으니,
frozen column 되기 전의 다른 chapter들에 이슈를 만들어두겠습니다!

**Comment by YOUNGZOO** [comment]
확인했습니다, 감사합니다! 혹시 제가 요청한이후에 올리신 이슈들 assign해서 진행해도 되는걸까요?!

**Comment by rinthel** [comment]
넵 마음 가시는대로 assign 하셔서 진행하시면 되겠습니다 :)
