### ISSUE TITLE
어색한 표현들을 고치고 싶습니다.

### ISSUE THREAD

**Issue by plzfday** [rinthel/rust-lang-book-ko#206]
안녕하세요. 러스트를 공부하면서 이 책의 원문, 번역본의 도움을 많이 받았습니다. 추후에 러스트에 접하시는 분들이 영어로 인해 언어의 본질에 집중할 수 없는 상황이 오지 않도록 저도 기여를 하고 싶습니다.

번역 자체는 다 끝난 것 같기 때문에 제가 이 책을 읽으면서 눈에 띄였던 어색한 표현들을 고치고 싶은데 어떤 식으로 참여할 수 있을까요? 이슈 탭을 사용해야 할 것 같긴 한데, 어떤 형식으로 이슈를 만들면 될까요?

**Comment by rinthel** [comment]
안녕하세요! 😄
collaborator로 등록해드렸습니다. 수정후 PR 올려주시면 리뷰후 반영하도록 하겠습니다!
감사합니다!

**Comment by rinthel** [comment]
오타 수정이나 오역 수정은 이슈 없이 진행하셔도 괜찮을 거 같고, 한 절이나 장 단위로 전체적인 수정이라면 장 단위의 이슈를 등록해두시고 진행하시면 될것 같습니다.
