### ISSUE TITLE
번영 참여 요청

### ISSUE THREAD

**Issue by octave08** [rinthel/rust-lang-book-ko#209]
안녕하세요, 이번에 러스트 공부함에 있어서 이 번역글을 통해 많은 도움을 받았습니다. 감사합니다.
이 과정에서 발견한 일부 오타에 대한 수정과 새로 추가된 내용들을 번역하려고 합니다. 
참여 가능할까요?

**Comment by rinthel** [comment]
넵 환영합니다!
collaborator로 등록해두겠습니다.
