### ISSUE TITLE
3장 번역을 맡아보고 싶습니다.

### ISSUE THREAD

**Issue by sprinter89** [rinthel/rust-lang-book-ko#212]
러스트 프로그래밍 언어에 큰 흥미가 생겨 문서들을 찾아 보았는데, 마침 한국어판으로 the book이 번역되고 있어서 저도 한번 참여해보고자 합니다. 프로그래밍 경험이 많지 않지만 제가 완전히 이해한 3장 내용을 맡아도 될까요??

**Comment by rinthel** [comment]
늦게 답변드려 죄송합니다. 물론 환영합니다! collaborator로 초대해드렸습니다~

**Comment by rinthel** [comment]
이후 작업은 https://github.com/rust-kr/doc.rust-kr.org 에서 진행할 예정입니다. 참고 부탁드릴게요~

**Comment by sprinter89** [comment]
요즘 계속되는 시험과 학업 일정으로 인해 번역 작업은 더 이상 참여하지 못할 듯합니다. 정말 죄송합니다. 앞으로도 힘내주셨으면 좋겠습니다.
