### ISSUE TITLE
2018-edition 번역에 참여하고 싶습니다

### ISSUE THREAD

**Issue by tantara** [rinthel/rust-lang-book-ko#214]
second-edition까지 번역이 완료된 것으로 보이는데 2018-edition에서 번역 완료되지 않은 챕터 있으면 참여하고 싶습니다!

**Comment by rinthel** [comment]
환영합니다! collaborator로 초대드렸습니다. 원하시는 챕터 이슈를 만드시고 브랜치를 따서 작업한 뒤에 pull-request 요청하시면 리뷰 후 merge 하겠습니다.
참고로, 2018년 버전의 대부분은 2nd 버전과 유사하므로, 2nd 버전을 복붙 하신 다음에 변경된 지점을 보면서 고쳐 나가는걸 추천드립니다.

**Comment by tantara** [comment]
안녕하세요 @rinthel,

원본 repo ([rust-lang/book](https://github.com/rust-lang/book))의 2018-edition 모든 문서가 아래와 같은 메세지로 바뀌어있는데요. rust-lang-book-ko의 2018-edition를 기준으로 번역하면 될까요?

[예시] [2018-edition/src/foreword.md](https://github.com/rust-lang/book/blob/master/2018-edition/src/foreword.md)

# Foreword

The 2018 edition of the book is no longer distributed with Rust's documentation.

If you came here via a link or web search, you may want to check out [the current
version of the book](../foreword.html) instead.

If you have an internet connection, you can [find a copy distributed with
Rust
1.30](https://doc.rust-lang.org/1.30.0/book/2018-edition/foreword.html).

**Comment by rinthel** [comment]
@tantara 일단은 원본 repo 보다는 이 repo를 기준으로 진행해주시면 되겠습니다. 이 repo에도 `2018-edition` 디렉토리 내용은 전부 비어있습니다. `src` 에 있는걸 기준으로 해주시면 됩니다. 추후에 원본 문서를 일괄적으로 업데이트할 때 원본의 변경된 지점을 보고, 바뀐 부분을 번역에도 적용할 예정입니다 :D
