### ISSUE TITLE
안녕하세요. 번역에 참여하고 싶습니다

### ISSUE THREAD

**Issue by cpprhtn** [rinthel/rust-lang-book-ko#218]
C++에서 rust로 넘어가는 학생입니다.

공부중에 번역이 덜 된 부분이 보이네요. 

ex) ch04-01의 마지막 코드의 주석부분
  // len() returns the length of a String.
-> len() 함수는 문자열의 길이를 반환합니다.

제가 직접 requests 하면 더 좋긴하겠습니다 :)

그리구 2018-edition 번역에도 참가하고싶습니다.

감사합니다

**Comment by rinthel** [comment]
환영합니다! collaborator로 등록해두었습니다. 번역해보실 챕터를 이슈로 만들어주시고 작업하신 뒤 pull request 보내주세요. 대부분의 챕터가 second edition과 거의 유사하므로 일단 복붙 하신 다음에 변경된 지점을 리뷰하는 식으로 진행하시면 됩니다!
