### ISSUE TITLE
원본 문서 업데이트

### ISSUE THREAD

**Issue by rinthel** [rinthel/rust-lang-book-ko#234]
- 현재 문서 버전: #a203290
- 목표 문서 버전: #77092be
- [x] 번역 안된 문서들의 일괄 변경
- [x] 번역된 문서들의 변경 내용 확인 및 번역본 수정
- [x] 2018년본 빌드 확인
- [ ] 2nd본 빌드 확인

**Comment by rinthel** [comment]
#236

**Comment by soilSpoon** [comment]
2nd본은 앞으로도 한동안 계속 사용하는 건가요?

**Comment by rinthel** [comment]
@soilSpoon 넵 현재 2018본은 번역이 많이 안되어 있는 상태라서요

**Comment by rinthel** [comment]
#237

**Comment by rinthel** [comment]
#242
