### ISSUE TITLE
브랜치 정리

### ISSUE THREAD

**Issue by mate131909** [rinthel/rust-lang-book-ko#235]
현재 몇 년간 방치된 브랜치가 좀 있는데, 불필요한 브랜치가 맞는다면 한번 정리하는 게 좋을 것 같습니다

**Comment by rinthel** [comment]
@mate131909 좋습니다! 이것도 제가 진행하겠습니다

**Comment by rinthel** [comment]
머지된 브랜치 정리
- feature/#2_4-3-translation
- jdkim/ch13 (#116)
- jdkim/ch13-re
- frozen-ch06 (#15)
- frozen-ch06-01 (#43)

**Comment by rinthel** [comment]
안쓰는 브랜치 정리
- word-replace

**Comment by rinthel** [comment]
수정 반영된 브랜치 
- ch17 => #130

**Comment by rinthel** [comment]
오래된 원본 문서 브랜치
- nostarch-ch14

**Comment by rinthel** [comment]
오래된 번역 브랜치
- chapter05
