### ISSUE TITLE
Discussions 또는 Slack, Discord 등을 사용해 질문/아이디어 제시 등이 가능하게 만들기

### ISSUE THREAD

**Issue by soilSpoon** [rinthel/rust-lang-book-ko#240]
현재 질문하고 싶은 내용을 물어볼 공간이 없어 어떡해야 할지 잘 모르겠습니다. 😭 

그래서 Discussions 같은 기능이 있으면 좋을 것 같습니다.

## Reference
[Quickstart for GitHub Discussions
](https://docs.github.com/en/free-pro-team@latest/discussions/quickstart)

**Comment by rinthel** [comment]
넵 시간나면 붙여보겠습니다- README 업데이트를 한번 해야되는데 그거랑 같이 진행해볼게요

**Comment by rinthel** [comment]
discussions을 열어봤습니다.
