### ISSUE TITLE
7장 1 mod-and-the-filesystem 오류가 있습니다.

### ISSUE THREAD

**Issue by km19809** [rinthel/rust-lang-book-ko#249]
현재 Cargo 버전인 1.49.0 기준으로 --bin이 cargo new의 기본 옵션임에도 현재 빌드된 버전은 잘못된 정보가 담겨 있습니다.
이에 수정이 필요할 것 같습니다.

번역본: https://github.com/rinthel/rust-lang-book-ko/blob/master/second-edition/src/ch07-01-mod-and-the-filesystem.md
`이전의 모든 장들에서 사용해왔던 --bin 옵션을 제거하면, 프로젝트는 라이브러리가 될 것입니다:`
원문: https://doc.rust-lang.org/1.30.0/book/second-edition/ch07-01-mod-and-the-filesystem.html
`We’ll call our library communicator. To create a library, pass the --lib option instead of --bin:`
Cargo 1.49.0 버전 Cargo new:
```
Rust's package manager

USAGE:
    cargo [+toolchain] [OPTIONS] [SUBCOMMAND]

OPTIONS:

(중략)
--bin                    Use a binary (application) template [default]
--lib                    Use a library template```

**Comment by rinthel** [comment]
감사합니다. 아마도 7장을 번역할 시점에 chapter freezing이 되지 않아서 생긴 오류인듯 하네요.

**Comment by rinthel** [comment]
수정되었습니다: 49ca40a
