### ISSUE TITLE
9장 오류

### ISSUE THREAD

**Issue by km19809** [rinthel/rust-lang-book-ko#251]
9장은 검수 이슈가 없어 새로 엽니다.

1. 9장 1절 'panic! 백트레이스 사용하기'의 여섯번째 문단은 다음과 같이 바꾸어야 합니다.
[빌드본 링크](https://rinthel.github.io/rust-lang-book-ko/ch09-01-unrecoverable-errors-with-panic.html#panic-%EB%B0%B1%ED%8A%B8%EB%A0%88%EC%9D%B4%EC%8A%A4-%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0)
`백트레이스를 읽는 요령은 위에서부터 시작하여 여러분이 작성한 파일이 보일때까지 읽는 것입니다. 그곳이 바로 문제를 읽으킨 지점입니다.`
=>
`백트레이스를 읽는 요령은 위에서부터 시작하여 여러분이 작성한 파일이 보일 때까지 읽는 것입니다. 그곳이 바로 문제를 일으킨 지점입니다.`
1. 9장 2절 '서로 다른 에러에 대해 매칭하기' 첫 문단에서 같은 말이 반복됩니다. 
[빌드본 링크](https://rinthel.github.io/rust-lang-book-ko/ch09-02-recoverable-errors-with-result.html#%EC%84%9C%EB%A1%9C-%EB%8B%A4%EB%A5%B8-%EC%97%90%EB%9F%AC%EC%97%90-%EB%8C%80%ED%95%B4-%EB%A7%A4%EC%B9%AD%ED%95%98%EA%B8%B0)
`만일 그밖의 이유로 File::open이 실패한 거라면, 예를 들어 파일을 열 권한이 없어서라면, 예를 들어 우리가 파일을 열 권한이 없기 때문이라면,`
1. 또한 위와 같은 곳(9장 2절) 네 번째 문단을 고쳐야 합니다.
`파일이 열수 없을 때, 다른 에러 메세지가 출력될 것입니다. `=>`파일을 열 수 없을 때, 다른 에러 메세지가 출력될 것입니다.`

감사합니다.

**Comment by km19809** [comment]
수정 감사합니다. 그런데 현재 9장 1절에 "문제를 *읽으킨* 지점입니다."가 여전히 남아 있는 것으로 보입니다.

**Comment by mate131909** [comment]
마저 수정했습니다.
