### ISSUE TITLE
rust-kr 로 repository 옮기기

### ISSUE THREAD

**Issue by rinthel** [rinthel/rust-lang-book-ko#258]
논의가 필요한 부분이라 이쪽에 먼저 의견을 구해봅니다.

현재 이 repository는 2nd edition 버전이 빌드되어 제 github page에 올라가고 있는데요,
어느덧 2018 edition 도 절반가량 번역이 되어 번역이 완료된 페이지만이라도 빌드를 해서 올리면
어떨까 싶습니다.

저는 한국 러스트 사용자 모임 페이지가 이미 있는 상태니 그 도메인 상에서
2018 edition 버전을 배포하는게 좋지 않을까 하는데요,
이 repository는 이쯤에서 freezing 하면서 2nd edition의 오타 수정 정도로만 유지를 하고,
rust-kr github 으로 이 repository를 fork해서 그쪽에서 2018 edition의 나머지 번역 및
배포를 관리해보는건 어떨까요.

@mate131909 님 의견 부탁드립니다. 찬성하신다면 제가 rust-kr 운영하시는 분에게 한번 의견을
물어보도록 하죠.

**Comment by mate131909** [comment]
전 찬성입니다!

**Comment by rinthel** [comment]
넵 그러면 rust-kr 쪽에 문의를 해보겠습니다!

**Comment by rinthel** [comment]
https://github.com/rust-kr/doc.rust-kr.org

앞으로의 작업은 여기에서 진행하는 것으로 하겠습니다!
