### ISSUE TITLE
mdbook build 전 preprocessor 같은걸 만들 수 있을까요?;

### ISSUE THREAD

**Issue by rinthel** [rinthel/rust-lang-book-ko#27]
번역을 진행하다보면 용어를 한글로 옮길때 섣불리 결정하기 힘든 경우가 꽤 생기는데요, 우리가 toml 같은 포맷으로 (영어로된 용어) = (번역된 용어)의 pair로 되어있는 사전을 하나 만들고, md 파일 내의 용어들을 일반적인 markdown 포맷에서 사용하지 않는 태그 같은걸로 묶어서, mdbook build 전에 일괄적으로 바꿔버리는 그런 기능이 있으면 편하지 않을까 생각하고 있습니다;

예를 들면, 사전에는 이렇게 되어있고,
```toml
[dictionary]
immutable = "불변"
reference = "참조자"
```

우리의 소스 파일이 이렇게 생겼다면,
```markdown
변수가 기본적으로 $$immutable$$인 것처럼, $$reference$$도 마찬가지입니다.
```

mdbook build를 하기 전에 아래처럼 바꿔서 빌드를 한다면 편할것 같아요.
```markdown
변수가 기본적으로 불변인 것처럼, 참조자도 마찬가지입니다.
```

이런 비슷한 기능을 쓸 수 있는 방법이 뭐가 있을까요? mdbook 개발자한테 플러그인 기능 언제 되냐고 물어볼까요?; 그냥 만들어야 할까요...;

**Comment by jenix21** [comment]
mdbook 에는 딱히 전처리 기능은 없어보이네요.
http://azerupi.github.io/mdBook/cli/cli-tool.html

ci 빌드 스크립트를 보면, mdbook test 전에 spellcheck 스크립트를 돌리는데요.
필요하다면 이런식으로 mdbook 실행전에 스크립트를 돌려야 하지 않을까요.

https://github.com/rinthel/rust-lang-book-ko/blob/master/ci/build.sh
```bash
cd second-edition
bash spellcheck.sh list
mdbook test
mdbook build
cargo run --bin lfp src
```

https://github.com/rinthel/rust-lang-book-ko/blob/master/second-edition/spellcheck.sh

**Comment by rinthel** [comment]
음 사전 파일의 단어로 replacement를 해줄 커맨드라인 툴과 빌드 스크립트로 어찌어찌 해볼만하겠군요.

**Comment by rinthel** [comment]
[https://github.com/rinthel/word_replace.git](https://github.com/rinthel/word_replace.git)
러스트 프로그래밍 연습 겸사겸사 이런걸 만들어보았습니다.

##기능
- toml 파일로 된 사전을 읽습니다.
- 소스 디렉토리에 있는 파일을 읽어서, `@@`로 둘러쌓인 단어를 찾으면,
   사전에서 이걸 찾아 대응되는 단어로 바꿔줍니다.
- 대응되는 단어가 한글이고, 이 단어 뒤에도 한글이 붙어있다면, 뒤에 붙어있는 말을 조사로 간주합니다.
- 이 조사를 toml 안에서 찾아보고 받침이 있고없고에 따라 조사를 바꿔 달아줍니다.

##사용법
- `cargo install word_replace`로 인스톨해서 사용할 수 있습니다.

조만간 시간날 때 이걸로 정의하기 애매한 용어들을 사전으로 만들어서 잘 되는지 테스트 해보겠습니다~
