### ISSUE TITLE
second-edition/src/ch08-01-vectors.md Listing 8-7 "유효하지 않은 참조자" 예제 중 누락 발견.

### ISSUE THREAD

**Issue by jeremyko** [rinthel/rust-lang-book-ko#302]
second-edition/src/ch08-01-vectors.md Listing 8-7 "유효하지 않은 참조자" 예제 중 누락 발견.

```rust
fn main() {
    let mut v = vec![1, 2, 3, 4, 5];
    let first = &v[0];
    v.push(6);
    println!("The first element is: {first}"); // !!! 이 라인이 예제에 존재해야 컴파일 에러가 발생되네요
}
```

Compiling cumbuffer_rust v0.1.0 (C:\Users\jerem\Downloads\mydev\rust_dev\cumbuffer_rust)
error[E0502]: cannot borrow `v` as mutable because it is also borrowed as immutable
 --> src\cumbuffer.rs:7:5
  |
6 |     let first = &v[0];
  |                  - immutable borrow occurs here
7 |     v.push(6);
  |     ^^^^^^^^^ mutable borrow occurs here
8 |     println!("The first element is: {first}");
  |                                      ----- immutable borrow later used here

감사히 보고 있습니다

**Comment by rinthel** [comment]
음 확인해보니 말씀해주신 예제는 최신 버전의 8-6 예제인것 같아요.

https://rust-kr.github.io/doc.rust-kr.org/ch08-01-vectors.html

이 저장소는 완역된 2nd edition만 유지보수하고 있고 여기의 8-7 예제는 `println!` 대신 immutable borrow -> mutable borrow를 쓰고 있습니다.

https://rinthel.github.io/rust-lang-book-ko/ch08-01-vectors.html
