### ISSUE TITLE
메소드 설명에서 함수 대신 사용하는 이유 : 오역 발견

### ISSUE THREAD

**Issue by jeremyko** [rinthel/rust-lang-book-ko#303]
https://rinthel.github.io/rust-lang-book-ko/ch05-03-method-syntax.html

함수 대신 메소드를 이용하면 생기는 주요 잇점은, 메소드 문법을 이용하여 모든 메소드 시그니처 
내에서마다 self의 타입을 반복하여 타이핑하지 않아도 된다는 점과 더불어, 조직화에 관한 점입니다. 

==> 원문 
The main reason for using methods instead of functions, in addition to providing 
method syntax and not having to repeat the type of self in every method’s signature, is for organization. 

메소드 시그니쳐에는 self 입력이 반복되야 하므로 오역이라고 볼수 있네요 

--> 이걸 좀 의역 하자면 
함수를 사용하면, 메소드 구문 제공 및 모든 시그니처 내에 self 를 반복 입력 할 필요가 없다. 
그럼에도 함수 대신 method 를 사용하는 주된 이유는 코드 구성을 위함이다.

**Comment by rinthel** [comment]
좋은 제안 감사합니다! 반영하였습니다 👍
