### ISSUE TITLE
arms의 한국말 번역...

### ISSUE THREAD

**Issue by ParkHanbum** [rinthel/rust-lang-book-ko#55]
https://github.com/rust-lang/book/issues/906

양키들은 function의 내용을 body라고 쓰죠. 
여기에서 파생된 말장난으로 match의 body를 arms라고 하나 봅니다.

**Comment by rinthel** [comment]
아, 저도 고민하다가 sarojaba님이 운영하시던 1버전에는 '팔'로 되어있는걸 보고,
저도 그냥 '팔'이라고 할까... 고민좀 하다가 사전을 뒤적여보니,
'(나무나 강 따위의) 갈래' 라는 말이 있길래, 제가 번역한 버전에는 '갈래'로 정리해봤습니다.
'갈래'는 어떠신지요? ㅎㅎ

**Comment by ParkHanbum** [comment]
@rinthel  좋군요. 의미가 통하는 것 같습니다. 
번역을 할 때, 의미를 옮기는 것에 대해 고민이 많아지게 되는데 
가끔은 단어 그 자체가 의미를 갖는 경우가 있죠.
예를 들어, Rustceans은 의미를 해석하면 "러스트사용자"를 지칭하는 은어인데 
이것을 "러스트사용자"로 옮길지 아니면 Rustceans로 사용할지 같은 겁니다. 

전에 토의한 bind와 비슷하게, 
우리가 bind를 어떤 의미로 번역하게 되면 이를 읽는 사람들은 번역된 내용을 학습하여
'bind'에 말 그대로 bind 되버리게 되는게 문제라고 생각합니다. 

이 경우 우리가 arms를 팔 혹은 갈래로 번역을 하게 되면, 그 의미가 bind되기 때문에
이 문서를 통해 rust를 공부하게 될 수도 있는 사람들이 match를 다루다가 의문이 생겨 
검색을 하게 됐을때 '팔' 혹은 '갈래'로 검색을 할 수 있는 자료는 오직 한국 자료뿐이죠. 

단적으로 "rust match arms"을 검색어로 지정해 구글 검색을 하는 것과
"rust match (팔 or 갈래)"로 검색의 차이는 큽니다. 

때문에 지금든 생각은 둘을 함께 표기하거나 아니면 그냥 영어를 표기하는게 
어떨까 싶습니다.

**Comment by rinthel** [comment]
검색 관련 문제에 대해 공감합니다 😃 
하지만 영문 병기를 매번 해주는 것에 대해서는 고민이 좀 생기더군요. 문서가 읽기 좋지 않은 모양새가 될 수 있고, 길어지기도 하니까요; 그래서 용어가 처음 나왔을때 영문 병기를 한번 해주고, 그 뒤로는 한글을 이용하는 식으로 썼는데,
지금 생각으로서는 영어 - 한국어 용어 번역표 같은걸 따로 제공해서 독자들이 혹 영어 원문으로는 어떻게 쓰는지 궁금한 한국어 단어가 나올 경우 바로 찾아볼 수 있게끔 하는건 어떨까 싶기도 합니다.

**Comment by ParkHanbum** [comment]
@rinthel 그것도 문제긴 하네요. 
말씀하신 대로 처음에는 역주라도 달아서 영문 병기를 한번 하면 될 것 같네요.
