### ISSUE TITLE
안녕하세요 번역 작업에 참여하고 싶습니다.

### ISSUE THREAD

**Issue by JunoJunho** [rinthel/rust-lang-book-ko#72]
안녕하세요.

번역작업에 같이 참여해보고 싶습니다.

현재 상황은 많은 내용이 번역이 완료된 것 같은데 도울 작업이 있다면 돕고 싶습니다.

**Comment by rinthel** [comment]
환영합니다! 지금은 한 40% 쯤? 진행된 상태입니다 ㅎㅎ 갈길이 멀죠
최신 문서를 번역하는것도 좋고, 번역본 검토도 좋습니다-

**Comment by JunoJunho** [comment]
옙 감사합니다. 그러면 제가 원하는 부분을 잡아서 진행하면 될까요?

**Comment by rinthel** [comment]
넵 원하시는 issue에 직접 assign하시고 진행하신 뒤 pull request 날려주시면 됩니다-

**Comment by JunoJunho** [comment]
넵 우선 이 이슈는 클로즈 하겠습니다~
