### ISSUE TITLE
1장 Introduction

### ISSUE THREAD

**Issue by JunoJunho** [rinthel/rust-lang-book-ko#77]
1장 Introduction 파트가 아직 번역이 되지 않아서, 초벌 번역을 진행하고자 합니다.

**Comment by rinthel** [comment]
앗, 우선 이걸 봐주세요:
https://github.com/rust-lang/book/projects/1

이게 원본 저장소에서 현재 어느정도까지 진행되고 있는지를 알려주는 게시판인데,
보시면 아시겠지만 chapter 1은 이제 영문 초본이 나온 상태입니다.

현재 영문 초본 pull request가 원본 저장소에 올라와있는데,
https://github.com/rust-lang/book/pull/957/files

거의 모든 내용이 다시 쓰여지고 있습니다;;; 지금 번역해도 나중에 새로 번역해야 하는 모양이 될 가능성이 높지요. 그래서 frozen chapter라고 적혀있는 chapter 위주로 번역을 진행했던 것이구요.

현재 번역이 안된 챕터 중에는 frozen chapter가 없지만, frozen에 최대한 가까운 chapter들 위주로 번역하기 위해 제가 이슈를 관리하는 중입니다.

그러니 새로운 챕터 번역은 가급적이면 제가 만들어둔 이슈를 이용하시면 좋겠습니다-
