### ISSUE TITLE
어느새 모든 chapter들이 frozen 되었군요

### ISSUE THREAD

**Issue by rinthel** [rinthel/rust-lang-book-ko#92]
아직 번역이 안된 chapter들의 원본 진행 상황을 보러 오리지널 repo에 들어가봤더니 모든 chapter들이 frozen 되어서, 다시한번 대대적으로 번역 안된 문서들을 업데이트했습니다 (커밋 기준: https://github.com/rust-lang/book/commit/b56c8f0994e81f9caadcadfcf2c63d17096738b4)

이제 번역 안된 chapter / section에 대해 자유롭게 issue를 만들고, 브랜치를 뽑아서 번역해도 될듯 합니다.

**Comment by WonbaeLee** [comment]
번역 작업에 힘써주셔서 감사합니다!!

**Comment by Oslint** [comment]
언제나 잘 보고 있습니다. 번역 해주셔서 감사합니다!
그리고 혹시 TRPL 2018 edition도 번역 예정에 있으신가요?

**Comment by rinthel** [comment]
@Oslint 응원 감사드립니다!
현재로서는 우선 Second Edition에라도 집중해야 할거 같구요 ㅎㅎ
2018 Edition을 흘끗 보니 아직은 Second Edition을 복붙해서 준비를 하고 있는것 같더군요.
내용이 좀 추가되거나 달라지는 때가 오고, 그때 Second Edition쪽 마무리가 되면 한번 생각해보겠습니다-
